<?php
/**
 * @category     Reflektion
 * @package      Reflektion_Catalogexport
 * @website      http://www.reflektion.com/ <http://www.reflektion.com/>
 * @createdOn    27/06/17
 * @time:        12:07 PM
 * @license      https://opensource.org/licenses/OSL-3.0
 * @description  For Cron Minute values
 */
namespace Reflektion\Catalogexport\Model\System\Config;

class Minute implements \Magento\Framework\Option\ArrayInterface
{
    /**
     * @return array
     */
    public function toOptionArray()
    {
        return [
            ['value' => '*', 'label' => __('Every minute (*)')],
            ['value' => '*/2', 'label' => __('Every 2 minutes (*/2)')],
            ['value' => '*/3', 'label' => __('Every 3 minutes (*/3)')],
            ['value' => '*/4', 'label' => __('Every 4 minutes (*/4)')],
            ['value' => '*/5', 'label' => __('Every 5 minutes (*/5)')],
            ['value' => '*/6', 'label' => __('Every 6 minutes (*/6)')],
            ['value' => '*/7', 'label' => __('Every 7 minutes (*/7)')],
            ['value' => '*/8', 'label' => __('Every 8 minutes (*/8)')],
            ['value' => '*/9', 'label' => __('Every 9 minutes (*/9)')],
            ['value' => '*/10', 'label' => __('Every 10 minutes (*/10)')],
            ['value' => '*/11', 'label' => __('Every 11 minutes (*/11)')],
            ['value' => '*/12', 'label' => __('Every 12 minutes (*/12)')],
            ['value' => '*/13', 'label' => __('Every 13 minutes (*/13)')],
            ['value' => '*/14', 'label' => __('Every 14 minutes (*/14)')],
            ['value' => '*/15', 'label' => __('Every 15 minutes (*/15)')],
            ['value' => '*/16', 'label' => __('Every 16 minutes (*/16)')],
            ['value' => '*/17', 'label' => __('Every 17 minutes (*/17)')],
            ['value' => '*/18', 'label' => __('Every 18 minutes (*/18)')],
            ['value' => '*/19', 'label' => __('Every 19 minutes (*/19)')],
            ['value' => '*/20', 'label' => __('Every 20 minutes (*/20)')],
            ['value' => '*/21', 'label' => __('Every 21 minutes (*/21)')],
            ['value' => '*/22', 'label' => __('Every 22 minutes (*/22)')],
            ['value' => '*/23', 'label' => __('Every 23 minutes (*/23)')],
            ['value' => '*/24', 'label' => __('Every 24 minutes (*/24)')],
            ['value' => '*/25', 'label' => __('Every 25 minutes (*/25)')],
            ['value' => '*/26', 'label' => __('Every 26 minutes (*/26)')],
            ['value' => '*/27', 'label' => __('Every 27 minutes (*/27)')],
            ['value' => '*/28', 'label' => __('Every 28 minutes (*/28)')],
            ['value' => '*/29', 'label' => __('Every 29 minutes (*/29)')],
            ['value' => '*/30', 'label' => __('Every 30 minutes (*/30)')],
            ['value' => '*/31', 'label' => __('Every 31 minutes (*/31)')],
            ['value' => '*/32', 'label' => __('Every 32 minutes (*/32)')],
            ['value' => '*/33', 'label' => __('Every 33 minutes (*/33)')],
            ['value' => '*/34', 'label' => __('Every 34 minutes (*/34)')],
            ['value' => '*/35', 'label' => __('Every 35 minutes (*/35)')],
            ['value' => '*/36', 'label' => __('Every 36 minutes (*/36)')],
            ['value' => '*/37', 'label' => __('Every 37 minutes (*/37)')],
            ['value' => '*/38', 'label' => __('Every 38 minutes (*/38)')],
            ['value' => '*/39', 'label' => __('Every 39 minutes (*/39)')],
            ['value' => '*/40', 'label' => __('Every 40 minutes (*/40)')],
            ['value' => '*/41', 'label' => __('Every 41 minutes (*/41)')],
            ['value' => '*/42', 'label' => __('Every 42 minutes (*/42)')],
            ['value' => '*/43', 'label' => __('Every 43 minutes (*/43)')],
            ['value' => '*/44', 'label' => __('Every 44 minutes (*/44)')],
            ['value' => '*/45', 'label' => __('Every 45 minutes (*/45)')],
            ['value' => '*/46', 'label' => __('Every 46 minutes (*/46)')],
            ['value' => '*/47', 'label' => __('Every 47 minutes (*/47)')],
            ['value' => '*/48', 'label' => __('Every 48 minutes (*/48)')],
            ['value' => '*/49', 'label' => __('Every 49 minutes (*/49)')],
            ['value' => '*/50', 'label' => __('Every 50 minutes (*/50)')],
            ['value' => '*/51', 'label' => __('Every 51 minutes (*/51)')],
            ['value' => '*/52', 'label' => __('Every 52 minutes (*/52)')],
            ['value' => '*/53', 'label' => __('Every 53 minutes (*/53)')],
            ['value' => '*/54', 'label' => __('Every 54 minutes (*/54)')],
            ['value' => '*/55', 'label' => __('Every 55 minutes (*/55)')],
            ['value' => '*/56', 'label' => __('Every 56 minutes (*/56)')],
            ['value' => '*/57', 'label' => __('Every 57 minutes (*/57)')],
            ['value' => '*/58', 'label' => __('Every 58 minutes (*/58)')],
            ['value' => '*/59', 'label' => __('Every 59 minutes (*/59)')],
            ['value' => '0', 'label' => __('At minute 0')],
            ['value' => '1', 'label' => __('At minute 1')],
            ['value' => '2', 'label' => __('At minute 2')],
            ['value' => '3', 'label' => __('At minute 3')],
            ['value' => '4', 'label' => __('At minute 4')],
            ['value' => '5', 'label' => __('At minute 5')],
            ['value' => '6', 'label' => __('At minute 6')],
            ['value' => '7', 'label' => __('At minute 7')],
            ['value' => '8', 'label' => __('At minute 8')],
            ['value' => '9', 'label' => __('At minute 9')],
            ['value' => '10', 'label' => __('At minute 10')],
            ['value' => '11', 'label' => __('At minute 11')],
            ['value' => '12', 'label' => __('At minute 12')],
            ['value' => '13', 'label' => __('At minute 13')],
            ['value' => '14', 'label' => __('At minute 14')],
            ['value' => '15', 'label' => __('At minute 15')],
            ['value' => '16', 'label' => __('At minute 16')],
            ['value' => '17', 'label' => __('At minute 17')],
            ['value' => '18', 'label' => __('At minute 18')],
            ['value' => '19', 'label' => __('At minute 19')],
            ['value' => '20', 'label' => __('At minute 20')],
            ['value' => '21', 'label' => __('At minute 21')],
            ['value' => '22', 'label' => __('At minute 22')],
            ['value' => '23', 'label' => __('At minute 23')],
            ['value' => '24', 'label' => __('At minute 24')],
            ['value' => '25', 'label' => __('At minute 25')],
            ['value' => '26', 'label' => __('At minute 26')],
            ['value' => '27', 'label' => __('At minute 27')],
            ['value' => '28', 'label' => __('At minute 28')],
            ['value' => '29', 'label' => __('At minute 29')],
            ['value' => '30', 'label' => __('At minute 30')],
            ['value' => '31', 'label' => __('At minute 31')],
            ['value' => '32', 'label' => __('At minute 32')],
            ['value' => '33', 'label' => __('At minute 33')],
            ['value' => '34', 'label' => __('At minute 34')],
            ['value' => '35', 'label' => __('At minute 35')],
            ['value' => '36', 'label' => __('At minute 36')],
            ['value' => '37', 'label' => __('At minute 37')],
            ['value' => '38', 'label' => __('At minute 38')],
            ['value' => '39', 'label' => __('At minute 39')],
            ['value' => '40', 'label' => __('At minute 40')],
            ['value' => '41', 'label' => __('At minute 41')],
            ['value' => '42', 'label' => __('At minute 42')],
            ['value' => '43', 'label' => __('At minute 43')],
            ['value' => '44', 'label' => __('At minute 44')],
            ['value' => '45', 'label' => __('At minute 45')],
            ['value' => '46', 'label' => __('At minute 46')],
            ['value' => '47', 'label' => __('At minute 47')],
            ['value' => '48', 'label' => __('At minute 48')],
            ['value' => '49', 'label' => __('At minute 49')],
            ['value' => '50', 'label' => __('At minute 50')],
            ['value' => '51', 'label' => __('At minute 51')],
            ['value' => '52', 'label' => __('At minute 52')],
            ['value' => '53', 'label' => __('At minute 53')],
            ['value' => '54', 'label' => __('At minute 54')],
            ['value' => '55', 'label' => __('At minute 55')],
            ['value' => '56', 'label' => __('At minute 56')],
            ['value' => '57', 'label' => __('At minute 57')],
            ['value' => '58', 'label' => __('At minute 58')],
            ['value' => '59', 'label' => __('At minute 59')],
        ];
    }
}
